# financials scientific libs python 2.7 build
FROM python:2
MAINTAINER Benjamin Lvovsky, ben@lvovsky.com
WORKDIR /usr/src/app

RUN apt-get update
RUN apt-get upgrade -y 
RUN apt-get install -y \
    libssl-dev \
    libffi-dev \
    libpng-dev \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
	git \
    wget \
    curl \
    vim \
    python-qt4 	    # not needed in non interactive version. TODO: remove for prod \
	libxml2-dev \
	libxslt-dev \
	python-dev \
	zlib1g-dev

RUN pip install --upgrade pip

RUN pip install numpy
RUN pip install pandas
RUN pip install pandas-datareader
RUN pip install Flask
RUN pip install scipy
RUN pip install seaborn
RUN pip install matplotlib
RUN pip install sympy
RUN pip install testtools
RUN pip install unittest2
RUN pip install python-dateutil
RUN pip install psycopg2
RUN pip install ptyprocess
RUN pip install Cython
RUN pip install PyYAML
RUN pip install qtconsole
RUN pip install nbconvert
RUN pip install nbformat

RUN pip install oauthlib
RUN pip install python-mimeparse
RUN pip install pytz
RUN pip install pyxdg
RUN pip install pyzmq
RUN pip install pyinotify
RUN pip install pyOpenSSL
RUN pip install pyparsing
RUN pip install pyrsistent
RUN pip install pyserial
RUN pip install pysqlite
RUN pip install Babel
RUN pip install fixtures
RUN pip install flake8
RUN pip install functools32
RUN pip install netifaces
RUN pip install nose
RUN pip install pandocfilters
RUN pip install patsy
RUN pip install pycrypto

RUN mkdir -p /usr/src/app
COPY . .

CMD ["python", "./markowitz.py"]
